//! Turns the selected chip feature into the two things the build needs from it:
//! a `memory.x` for the linker, and the `cfg` flags the source gates on.
//!
//! Only the pin count and the memory sizes reach the code — a part's package and
//! temperature grade are invisible to software, so `K8U6` and `K8T6` are one
//! feature. The AF map is keyed to the flash code, hence `chip_x4` / `x6` / `x8`
//! rather than one flag per part.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Every part of the series: feature name, bonded pins, flash and SRAM in KiB.
///
/// The flash code also gives the SRAM size (4 -> 4K, 6 -> 6K, 8 -> 8K), but both
/// are spelled out rather than derived — a future part that breaks the pattern
/// should be a new row here, not a special case in code.
const CHIPS: &[Chip] = &[
    Chip::new("gd32e230f4", 20, 16, 4),
    Chip::new("gd32e230f6", 20, 32, 6),
    Chip::new("gd32e230f8", 20, 64, 8),
    Chip::new("gd32e230e8", 24, 64, 8),
    Chip::new("gd32e230g4", 28, 16, 4),
    Chip::new("gd32e230g6", 28, 32, 6),
    Chip::new("gd32e230g8", 28, 64, 8),
    Chip::new("gd32e230k4", 32, 16, 4),
    Chip::new("gd32e230k6", 32, 32, 6),
    Chip::new("gd32e230k8", 32, 64, 8),
    Chip::new("gd32e230c4", 48, 16, 4),
    Chip::new("gd32e230c6", 48, 32, 6),
    Chip::new("gd32e230c8", 48, 64, 8),
];

/// Where the two memories live on every part of the series.
const FLASH_ORIGIN: &str = "0x08000000";
const RAM_ORIGIN: &str = "0x20000000";

struct Chip {
    feature: &'static str,
    pins: u32,
    flash_kb: u32,
    sram_kb: u32,
}

impl Chip {
    const fn new(feature: &'static str, pins: u32, flash_kb: u32, sram_kb: u32) -> Self {
        Self {
            feature,
            pins,
            flash_kb,
            sram_kb,
        }
    }

    /// The flash code, which is what the AF map differs by.
    fn flash_code(&self) -> char {
        self.feature.chars().last().expect("feature name is empty")
    }

    /// Whether Cargo enabled this part's feature.
    fn enabled(&self) -> bool {
        env::var_os(format!("CARGO_FEATURE_{}", self.feature.to_uppercase())).is_some()
    }
}

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    for flash_code in ['4', '6', '8'] {
        println!("cargo::rustc-check-cfg=cfg(chip_x{flash_code})");
    }
    for pins in [20, 24, 28, 32, 48] {
        println!("cargo::rustc-check-cfg=cfg(pins_{pins})");
    }

    let selected: Vec<&Chip> = CHIPS.iter().filter(|chip| chip.enabled()).collect();
    let chip = match selected.as_slice() {
        [chip] => chip,
        // A build script cannot see a `compile_error!`, and by the time one fires
        // the linker script is already missing, so the check lives here too.
        [] => panic!("select a chip: enable exactly one of the gd32e230* features"),
        several => panic!(
            "the gd32e230* features are mutually exclusive, but {} are enabled: {}",
            several.len(),
            several
                .iter()
                .map(|chip| chip.feature)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    };

    println!("cargo::rustc-cfg=chip_x{}", chip.flash_code());
    println!("cargo::rustc-cfg=pins_{}", chip.pins);

    // The linker resolves `INCLUDE memory.x` against the current directory first
    // and the search paths after, so a `memory.x` in the project root still wins
    // — that is the escape hatch for a board this table does not describe.
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    fs::write(
        out_dir.join("memory.x"),
        format!(
            "/* Generated by build.rs from the `{}` feature. */\n\
             MEMORY\n\
             {{\n\
             \x20   FLASH : ORIGIN = {}, LENGTH = {}K\n\
             \x20   RAM   : ORIGIN = {}, LENGTH = {}K\n\
             }}\n",
            chip.feature, FLASH_ORIGIN, chip.flash_kb, RAM_ORIGIN, chip.sram_kb
        ),
    )
    .expect("write memory.x");
    println!("cargo::rustc-link-search={}", out_dir.display());
}
