//! Direct memory access: five independent channels moving data without the core.
//!
//! [`DmaExt::split`] consumes the peripheral and hands out one [`Channel`] per
//! hardware channel:
//!
//! ```ignore
//! let channels = dp.dma.split(&mut rcu);
//! let ch0 = channels.ch0;
//! ```
//!
//! A channel is a unique ownership token — the only ones in existence are those
//! `split` produced, and a transfer takes one by value for as long as it runs, so
//! a channel cannot be driving two transfers at once.
//!
//! Channels share a register block but not registers: each touches only its own
//! `CHxCTL`/`CHxCNT`/`CHxPADDR`/`CHxMADDR`, which the channel number in the type
//! guarantees. The two genuinely shared registers stay safe by construction —
//! `INTF` is only ever read, and `INTC` is write-one-to-clear, so a channel
//! clearing its own flags cannot disturb another's.

use core::marker::PhantomData;

use gd32e2::gd32e230;

use crate::adc::Adc;
use crate::rcu::Rcu;
use crate::spi::{self, Spi};
use crate::usart::{self, Usart};

/// Channel priority when several channels contend for the bus.
///
/// Affects only arbitration latency, never the correctness of a single transfer.
#[allow(missing_docs)]
pub enum Prio {
    Low,
    Medium,
    High,
    UltraHigh,
}

/// Transfer direction, selecting the `DIR` bit.
pub(crate) enum Dir {
    /// Peripheral to memory.
    P2M,
    /// Memory to peripheral.
    M2P,
}

/// Width of one transferred unit, selecting `PWIDTH`/`MWIDTH`.
#[allow(missing_docs)]
pub enum Width {
    Bits8,
    Bits16,
    Bits32,
}

/// One DMA channel, identified by its number at the type level.
///
/// Cannot be constructed outside this module: the only channels that exist come
/// from [`DmaExt::split`], which is what makes a channel a unique token.
pub struct Channel<const N: u8> {
    _marker: PhantomData<()>,
}

impl<const N: u8> Channel<N> {
    fn reg(&self) -> &gd32e230::dma::RegisterBlock {
        unsafe { &*gd32e230::Dma::ptr() }
    }
}

/// The raw per-channel register operations, generated by the `channels!` macro.
///
/// `pub(crate)`: these setters take raw addresses and start the channel, so
/// exposing them would let safe code point the hardware at arbitrary memory.
pub(crate) trait ChannelOps {
    fn configure(&mut self, dir: Dir, width: Width, prio: Prio);
    fn set_paddr(&mut self, addr: u32);
    fn set_maddr(&mut self, addr: u32);
    fn set_cnt(&mut self, cnt: u16);
    fn cnt(&self) -> u16;
    fn set_enabled(&mut self, enabled: bool);
    fn is_complete(&self) -> bool;
    fn is_error(&self) -> bool;
    fn clear_flags(&mut self);
}

macro_rules! channels {
    ($($N:literal => $ctl:ident, $cnt:ident, $paddr:ident, $maddr:ident,
                     $ftfif:ident, $errif:ident, $gifc:ident;)+) => {
        $(
            impl ChannelOps for Channel<$N> {
                /// Writes the whole of `CHxCTL` in one go: direction, width,
                /// priority, memory increment on, peripheral increment off, and
                /// M2M/circular/interrupts off.
                ///
                /// A single `write` (not `modify`) so unmentioned fields reset to
                /// zero — this clears any leftover bits when a channel is reused,
                /// and must run while `CHEN` is 0 (before the channel is enabled).
                fn configure(&mut self, dir: Dir, width: Width, prio: Prio) {
                    self.reg().$ctl().write(|w| {
                        let w = w.pnaga()
                                 .fixed()
                                 .mnaga()
                                 .increment()
                                 .m2m()
                                 .disabled()
                                 .cmen()
                                 .disabled()
                                 .errie()
                                 .disabled()
                                 .htfie()
                                 .disabled()
                                 .ftfie()
                                 .disabled();
                        let w = match dir {
                            Dir::P2M => w.dir().from_peripheral(),
                            Dir::M2P => w.dir().from_memory(),
                        };
                        let w = match width {
                            Width::Bits8 => w.mwidth().bits8().pwidth().bits8(),
                            Width::Bits16 => w.mwidth().bits16().pwidth().bits16(),
                            Width::Bits32 => w.mwidth().bits32().pwidth().bits32(),
                        };
                        match prio {
                            Prio::Low => w.prio().low(),
                            Prio::Medium => w.prio().medium(),
                            Prio::High => w.prio().high(),
                            Prio::UltraHigh => w.prio().very_high(),
                        }
                    });
                }
                /// Points the channel at the peripheral data register.
                fn set_paddr(&mut self, addr: u32) {
                    self.reg().$paddr().write(|w| unsafe { w.bits(addr) });
                }
                /// Points the channel at the memory buffer.
                fn set_maddr(&mut self, addr: u32) {
                    self.reg().$maddr().write(|w| unsafe { w.bits(addr) });
                }
                /// Sets how many transfers the channel performs.
                fn set_cnt(&mut self, cnt: u16) {
                    self.reg().$cnt().write(|w| w.cnt().bits(cnt));
                }
                /// Transfers still outstanding; counts down as the channel runs.
                fn cnt(&self) -> u16 {
                    self.reg().$cnt().read().cnt().bits()
                }
                /// Starts or stops the channel.
                fn set_enabled(&mut self, enabled: bool) {
                    self.reg().$ctl().modify(|_, w| w.chen().bit(enabled));
                }
                /// Whether the channel has finished its last transfer.
                fn is_complete(&self) -> bool {
                    self.reg().intf().read().$ftfif().bit_is_set()
                }
                /// Whether the channel hit a bus error.
                fn is_error(&self) -> bool {
                    self.reg().intf().read().$errif().bit_is_set()
                }
                /// Clears every interrupt flag of this channel.
                ///
                /// `INTC` is write-one-to-clear, so writing zeroes into the other
                /// channels' bits leaves them alone — this must never become a
                /// `modify`, which would read and write back their flags too.
                fn clear_flags(&mut self) {
                    self.reg().intc().write(|w| w.$gifc().set_bit());
                }
            }
        )+
    };
}

channels! {
    0 => ch0ctl, ch0cnt, ch0paddr, ch0maddr, ftfif0, errif0, gifc0;
    1 => ch1ctl, ch1cnt, ch1paddr, ch1maddr, ftfif1, errif1, gifc1;
    2 => ch2ctl, ch2cnt, ch2paddr, ch2maddr, ftfif2, errif2, gifc2;
    3 => ch3ctl, ch3cnt, ch3paddr, ch3maddr, ftfif3, errif3, gifc3;
    4 => ch4ctl, ch4cnt, ch4paddr, ch4maddr, ftfif4, errif4, gifc4;
}

/// A type usable as a DMA transfer unit, mapping to its [`Width`].
///
/// Bounds the peripheral's word type so only `u8`/`u16`/`u32` qualify, and
/// carries the [`Width`] that a channel writes into `PWIDTH`/`MWIDTH`.
pub trait DmaWord {
    /// The transfer width of this type.
    const WIDTH: Width;
}

impl DmaWord for u8 {
    const WIDTH: Width = Width::Bits8;
}
impl DmaWord for u16 {
    const WIDTH: Width = Width::Bits16;
}
impl DmaWord for u32 {
    const WIDTH: Width = Width::Bits32;
}

/// A peripheral channel `N` can read from, for peripheral-to-memory transfers.
///
/// Implemented only for the channel a peripheral's request line actually
/// reaches, so an impossible pairing fails to compile rather than producing a
/// transfer that is never requested.
pub trait DmaSrc<const N: u8> {
    /// The word type this peripheral transfers, fixing `PWIDTH`/`MWIDTH`.
    type Word: DmaWord;
    /// Address of the peripheral's data register.
    fn addr(&self) -> u32;
}

/// A peripheral channel `N` can write to, for memory-to-peripheral transfers.
///
/// The counterpart of [`DmaSrc`]; see there for why the channel is fixed.
pub trait DmaDst<const N: u8> {
    /// The word type this peripheral transfers, fixing `PWIDTH`/`MWIDTH`.
    type Word: DmaWord;
    /// Address of the peripheral's data register.
    fn addr(&self) -> u32;
}

// Request mapping, Table 8-3. Entries marked (1) apply while the corresponding
// remap bit in SYSCFG_CFG0 is clear — the state after reset — and (2) while it
// is set. Only the (1) mapping is implemented below: the two are mutually
// exclusive at runtime, so implementing both would make either choice compile
// while only one of them is actually wired. Peripherals without a HAL module
// are listed for completeness only.
//
//   Ch0: ADC(1), TIMER16_CH0(1), TIMER16_UP(1)
//   Ch1: ADC(2), SPI/I2S0_RX, USART0_TX(1), I2C0_TX, TIMER0_CH0, TIMER2_CH2,
//        TIMER16_CH0(2), TIMER16_UP(2)
//   Ch2: SPI/I2S0_TX, USART0_RX(1), I2C0_RX, TIMER0_CH1, TIMER2_CH3, TIMER2_UP,
//        TIMER5_UP, TIMER15_CH0(1), TIMER15_UP(1)
//   Ch3: SPI1_RX, USART0_TX(2), USART1_TX, I2C1_TX, TIMER0_CH3, TIMER0_TRIG,
//        TIMER0_COM, TIMER2_CH0, TIMER2_TRIG, TIMER15_CH0(2), TIMER15_UP(2)
//   Ch4: SPI1_TX, USART0_RX(2), USART1_RX, I2C1_RX, TIMER0_CH2, TIMER0_UP,
//        TIMER14_CH0, TIMER14_UP, TIMER14_TRIG, TIMER14_COM, TIMER14_CH1
macro_rules! dma_map {
    ($($Trait:ident<$N:literal> for $Ty:ty, $W:ty, $Periph:ty, $reg:ident, [$($gen:ident),*];)+) => {
        $(
            impl<$($gen),*> $Trait<$N> for $Ty {
                type Word = $W;
                fn addr(&self) -> u32 {
                    unsafe { (*<$Periph>::ptr()).$reg().as_ptr() as u32 }
                }
            }
        )+
    };
}

dma_map! {
    DmaSrc<0> for Adc, u16, gd32e230::Adc, rdata, [];

    DmaSrc<1> for Spi<gd32e230::Spi0, SCK, MISO, MOSI, spi::Byte>, u8, gd32e230::Spi0, data, [SCK, MISO, MOSI];
    DmaSrc<1> for Spi<gd32e230::Spi0, SCK, MISO, MOSI, spi::Word>, u16, gd32e230::Spi0, data, [SCK, MISO, MOSI];
    DmaDst<1> for Usart<gd32e230::Usart0, TX, RX, usart::Byte>, u8, gd32e230::Usart0, tdata, [TX, RX];
    DmaDst<1> for Usart<gd32e230::Usart0, TX, RX, usart::Word>, u16, gd32e230::Usart0, tdata, [TX, RX];

    DmaDst<2> for Spi<gd32e230::Spi0, SCK, MISO, MOSI, spi::Byte>, u8, gd32e230::Spi0, data, [SCK, MISO, MOSI];
    DmaDst<2> for Spi<gd32e230::Spi0, SCK, MISO, MOSI, spi::Word>, u16, gd32e230::Spi0, data, [SCK, MISO, MOSI];
    DmaSrc<2> for Usart<gd32e230::Usart0, TX, RX, usart::Byte>, u8, gd32e230::Usart0, rdata, [TX, RX];
    DmaSrc<2> for Usart<gd32e230::Usart0, TX, RX, usart::Word>, u16, gd32e230::Usart0, rdata, [TX, RX];

    DmaSrc<3> for Spi<gd32e230::Spi1, SCK, MISO, MOSI, spi::Byte>, u8, gd32e230::Spi1, data, [SCK, MISO, MOSI];
    DmaSrc<3> for Spi<gd32e230::Spi1, SCK, MISO, MOSI, spi::Word>, u16, gd32e230::Spi1, data, [SCK, MISO, MOSI];
    DmaDst<3> for Usart<gd32e230::Usart1, TX, RX, usart::Byte>, u8, gd32e230::Usart1, tdata, [TX, RX];
    DmaDst<3> for Usart<gd32e230::Usart1, TX, RX, usart::Word>, u16, gd32e230::Usart1, tdata, [TX, RX];

    DmaDst<4> for Spi<gd32e230::Spi1, SCK, MISO, MOSI, spi::Byte>, u8, gd32e230::Spi1, data, [SCK, MISO, MOSI];
    DmaDst<4> for Spi<gd32e230::Spi1, SCK, MISO, MOSI, spi::Word>, u16, gd32e230::Spi1, data, [SCK, MISO, MOSI];
    DmaSrc<4> for Usart<gd32e230::Usart1, TX, RX, usart::Byte>, u8, gd32e230::Usart1, rdata, [TX, RX];
    DmaSrc<4> for Usart<gd32e230::Usart1, TX, RX, usart::Word>, u16, gd32e230::Usart1, rdata, [TX, RX];
}

// The bound is what restricts N to the five channels that have an impl.
#[allow(private_bounds)]
impl<const N: u8> Channel<N>
where
    Channel<N>: ChannelOps,
{
    /// Starts a memory-to-peripheral transfer, moving `buf` into `periph`.
    ///
    /// Takes the channel, `periph` and `buf` by value; none of the three are
    /// accessible again until [`Transfer::wait`] returns them. The transfer
    /// width follows from the peripheral's word type, so `buf` must match it.
    pub fn write_to<P: DmaDst<N>>(
        mut self,
        periph: P,
        buf: &'static [P::Word],
        prio: Prio,
    ) -> Transfer<N, P, &'static [P::Word]> {
        self.set_maddr(buf.as_ptr() as u32);
        self.set_paddr(periph.addr());
        self.set_cnt(buf.len() as u16);
        self.configure(Dir::M2P, <P::Word as DmaWord>::WIDTH, prio);
        self.set_enabled(true);
        Transfer {
            channel: self,
            periph,
            buf,
        }
    }
    /// Starts a peripheral-to-memory transfer, filling `buf` from `periph`.
    ///
    /// Takes the channel, `periph` and `buf` by value; none of the three are
    /// accessible again until [`Transfer::wait`] returns them — in particular,
    /// `buf` cannot be read before the transfer completes. The transfer width
    /// follows from the peripheral's word type, so `buf` must match it.
    pub fn read_from<P: DmaSrc<N>>(
        mut self,
        periph: P,
        buf: &'static mut [P::Word],
        prio: Prio,
    ) -> Transfer<N, P, &'static mut [P::Word]> {
        self.set_maddr(buf.as_mut_ptr() as u32);
        self.set_paddr(periph.addr());
        self.set_cnt(buf.len() as u16);
        self.configure(Dir::P2M, <P::Word as DmaWord>::WIDTH, prio);
        self.set_enabled(true);
        Transfer {
            channel: self,
            periph,
            buf,
        }
    }
}

/// A DMA transfer in progress, started by [`Channel::write_to`] or
/// [`read_from`](Channel::read_from).
///
/// Owns the channel, the peripheral and the buffer for as long as the transfer
/// runs; [`wait`](Transfer::wait) is the only way to get them back.
pub struct Transfer<const N: u8, P, BUF> {
    channel: Channel<N>,
    periph: P,
    buf: BUF,
}

// The bound is what restricts N to the five channels that have an impl.
#[allow(private_bounds)]
impl<const N: u8, P, BUF> Transfer<N, P, BUF>
where
    Channel<N>: ChannelOps,
{
    /// Blocks until the transfer completes, then returns the channel, the
    /// peripheral and the buffer.
    ///
    /// Does not check `ERRIF` — see the DMA entry in the project's conscious
    /// refusals for why a bus error is unreachable through this API.
    pub fn wait(mut self) -> (Channel<N>, P, BUF) {
        while !self.channel.is_complete() {}
        self.channel.set_enabled(false);
        self.channel.clear_flags();
        (self.channel, self.periph, self.buf)
    }
}

/// The DMA channels, as handed out by [`DmaExt::split`].
#[allow(missing_docs)]
pub struct Channels {
    pub ch0: Channel<0>,
    pub ch1: Channel<1>,
    pub ch2: Channel<2>,
    pub ch3: Channel<3>,
    pub ch4: Channel<4>,
}

/// Splits the DMA peripheral into its individual channels.
pub trait DmaExt {
    /// The channels this peripheral hands out.
    type Channels;

    /// Switches the DMA clock on and hands out the channels.
    ///
    /// Consumes the peripheral, so the channels it returns are the only ones
    /// that will ever exist.
    fn split(self, rcu: &mut Rcu) -> Self::Channels;
}

impl DmaExt for gd32e230::Dma {
    type Channels = Channels;
    fn split(self, rcu: &mut Rcu) -> Self::Channels {
        <gd32e230::Dma as crate::rcu::Enable>::enable(rcu);
        Channels {
            ch0: Channel {
                _marker: PhantomData,
            },
            ch1: Channel {
                _marker: PhantomData,
            },
            ch2: Channel {
                _marker: PhantomData,
            },
            ch3: Channel {
                _marker: PhantomData,
            },
            ch4: Channel {
                _marker: PhantomData,
            },
        }
    }
}
